extends: default
rules:
  document-start: {present: false}
  line-length: {max: 200, allow-non-breakable-words: true, allow-non-breakable-inline-mappings: true}
  truthy: {check-keys: false}
  indentation: {indent-sequences: consistent}
  comments: {min-spaces-from-content: 1}
  empty-lines: {max: 2}
  hyphens: {max-spaces-after: 1}
ignore: |
  **/node_modules/**
  **/.git/**
