version: '3.8'

services:
  # IPPAN Blockchain Node
  ippan-node:
    image: ghcr.io/dmrl789/ippan/ippan-node:latest
    container_name: ippan-node
    environment:
      - NODE_ID=ippan_production_node_001
      - VALIDATOR_ID=0000000000000000000000000000000000000000000000000000000000000001
      - RPC_HOST=0.0.0.0
      - RPC_PORT=8080
      - P2P_HOST=0.0.0.0
      - P2P_PORT=9000
      - P2P_BOOTNODES=http://
      - STORAGE_PATH=/var/lib/ippan/db
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    ports:
      - "8080:8080"  # RPC API
      - "9000:9000"  # P2P
    volumes:
      - node_data:/var/lib/ippan/db
    restart: unless-stopped
    networks:
      - ippan-network

  # Unified UI
  unified-ui:
    image: ghcr.io/dmrl789/ippan/unified-ui:latest
    container_name: unified-ui
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_GATEWAY_URL=https://ui.ippan.org/api
      - NEXT_PUBLIC_API_BASE_URL=https://ui.ippan.org/api
      - NEXT_PUBLIC_WS_URL=wss://ui.ippan.org/ws
      - NEXT_PUBLIC_ENABLE_FULL_UI=1
      - NEXT_PUBLIC_NETWORK_NAME=IPPAN-Devnet
    ports:
      - "3001:3000"  # UI
    restart: unless-stopped
    depends_on:
      - ippan-node
    networks:
      - ippan-network

  # API Gateway
  gateway:
    image: ghcr.io/dmrl789/ippan/gateway:latest
    container_name: gateway
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8081
      - NODE_RPC_URL=http://ippan-node:8080
      - GATEWAY_ALLOWED_ORIGINS=https://ui.ippan.org
    ports:
      - "8081:8081"  # Gateway API
    restart: unless-stopped
    depends_on:
      - ippan-node
    networks:
      - ippan-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - unified-ui
      - gateway
    networks:
      - ippan-network

volumes:
  node_data:

networks:
  ippan-network:
    driver: bridge
