# Simple Auto Deploy IPPAN
Import-Module Posh-SSH -ErrorAction SilentlyContinue

$SERVER1_IP = "188.245.97.41"
$SERVER2_IP = "135.181.145.174"

Write-Host "=== Simple Auto Deploy IPPAN ===" -ForegroundColor Cyan

# Function to try common rescue passwords
function Try-ConnectWithPasswords {
    param($ServerIP, $ServerName)
    
    # Common rescue passwords to try (these are often generated by Hetzner)
    $commonPasswords = @(
        "VgRfqNg3T4sx",  # From your existing scripts
        "root123",
        "rescue123",
        "hetzner123"
    )
    
    foreach ($password in $commonPasswords) {
        Write-Host "Trying password for $ServerName..." -ForegroundColor Yellow
        try {
            $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
            $credential = New-Object System.Management.Automation.PSCredential("root", $securePassword)
            
            $session = New-SSHSession -ComputerName $ServerIP -Credential $credential -AcceptKey -ConnectionTimeout 10
            
            if ($session) {
                Write-Host "✅ Connected to $ServerName with password!" -ForegroundColor Green
                return @{
                    Session = $session
                    Password = $password
                }
            }
        } catch {
            Write-Host "Failed with password: $password" -ForegroundColor Red
        }
    }
    
    return $null
}

# Try to connect to Server 1
Write-Host "Attempting to connect to Server 1..." -ForegroundColor Green
$server1Connection = Try-ConnectWithPasswords -ServerIP $SERVER1_IP -ServerName "Server 1"

if ($server1Connection) {
    Write-Host "✅ Connected to Server 1! Starting deployment..." -ForegroundColor Green
    
    # Read deployment commands
    $deployCommands = Get-Content "server1_deploy_commands.txt" -Raw
    
    # Execute deployment
    $deployResult = Invoke-SSHCommand -SessionId $server1Connection.Session.SessionId -Command $deployCommands -Timeout 1800
    
    if ($deployResult.ExitStatus -eq 0) {
        Write-Host "✅ Server 1 deployment completed!" -ForegroundColor Green
        Write-Host $deployResult.Output -ForegroundColor Cyan
    } else {
        Write-Host "⚠️ Server 1 deployment had issues" -ForegroundColor Yellow
        Write-Host "Error: $($deployResult.Error)" -ForegroundColor Red
    }
    
    # Check status
    $statusResult = Invoke-SSHCommand -SessionId $server1Connection.Session.SessionId -Command "docker ps --filter 'name=ippan' --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'" -Timeout 30
    if ($statusResult.ExitStatus -eq 0) {
        Write-Host "Server 1 service status:" -ForegroundColor Green
        Write-Host $statusResult.Output -ForegroundColor Cyan
    }
    
    Remove-SSHSession -SessionId $server1Connection.Session.SessionId
} else {
    Write-Host "❌ Could not connect to Server 1" -ForegroundColor Red
}

# Try to connect to Server 2
Write-Host ""
Write-Host "Attempting to connect to Server 2..." -ForegroundColor Green
$server2Connection = Try-ConnectWithPasswords -ServerIP $SERVER2_IP -ServerName "Server 2"

if ($server2Connection) {
    Write-Host "✅ Connected to Server 2! Starting deployment..." -ForegroundColor Green
    
    # Read deployment commands
    $deployCommands = Get-Content "server2_deploy_commands.txt" -Raw
    
    # Execute deployment
    $deployResult = Invoke-SSHCommand -SessionId $server2Connection.Session.SessionId -Command $deployCommands -Timeout 1800
    
    if ($deployResult.ExitStatus -eq 0) {
        Write-Host "✅ Server 2 deployment completed!" -ForegroundColor Green
        Write-Host $deployResult.Output -ForegroundColor Cyan
    } else {
        Write-Host "⚠️ Server 2 deployment had issues" -ForegroundColor Yellow
        Write-Host "Error: $($deployResult.Error)" -ForegroundColor Red
    }
    
    # Check status
    $statusResult = Invoke-SSHCommand -SessionId $server2Connection.Session.SessionId -Command "docker ps --filter 'name=ippan' --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'" -Timeout 30
    if ($statusResult.ExitStatus -eq 0) {
        Write-Host "Server 2 service status:" -ForegroundColor Green
        Write-Host $statusResult.Output -ForegroundColor Cyan
    }
    
    Remove-SSHSession -SessionId $server2Connection.Session.SessionId
} else {
    Write-Host "❌ Could not connect to Server 2" -ForegroundColor Red
}

# Test APIs
Write-Host ""
Write-Host "=== Testing APIs ===" -ForegroundColor Cyan
Start-Sleep -Seconds 30

try {
    $api1 = Invoke-WebRequest -Uri "http://$SERVER1_IP`:3000/health" -TimeoutSec 10 -UseBasicParsing 2>$null
    if ($api1.StatusCode -eq 200) {
        Write-Host "✅ Server 1 API is responding: $($api1.StatusCode)" -ForegroundColor Green
    } else {
        Write-Host "⚠️ Server 1 API returned status: $($api1.StatusCode)" -ForegroundColor Yellow
    }
} catch {
    Write-Host "❌ Server 1 API is not responding" -ForegroundColor Red
}

try {
    $api2 = Invoke-WebRequest -Uri "http://$SERVER2_IP`:3000/health" -TimeoutSec 10 -UseBasicParsing 2>$null
    if ($api2.StatusCode -eq 200) {
        Write-Host "✅ Server 2 API is responding: $($api2.StatusCode)" -ForegroundColor Green
    } else {
        Write-Host "⚠️ Server 2 API returned status: $($api2.StatusCode)" -ForegroundColor Yellow
    }
} catch {
    Write-Host "❌ Server 2 API is not responding" -ForegroundColor Red
}

Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "Deployment attempt completed. Check the results above." -ForegroundColor Green
Write-Host ""
Write-Host "If deployment failed, you can manually copy the commands from:" -ForegroundColor Yellow
Write-Host "- server1_deploy_commands.txt" -ForegroundColor White
Write-Host "- server2_deploy_commands.txt" -ForegroundColor White
