name: Security Suite

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript', 'rust' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        if: matrix.language == 'rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust Cache
        if: matrix.language == 'rust'
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Node.js
        if: matrix.language == 'javascript-typescript'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            apps/gateway/package-lock.json
            apps/unified-ui/package-lock.json

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{ matrix.language }}'

  dependency-scan:
    name: Dependency & Vulnerability Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run cargo audit
        id: cargo_audit
        run: |
          set +e
          cargo audit --json > cargo-audit-report.json
          audit_exit=$?
          set -e
          if [ $audit_exit -ne 0 ]; then
            echo "::warning::cargo audit exited with status $audit_exit. Continuing to parse results."
          fi
          critical=$(jq '.vulnerabilities.list[]? | select(.advisory.severity == "critical") | .package.name' cargo-audit-report.json | wc -l | tr -d ' ')
          high=$(jq '.vulnerabilities.list[]? | select(.advisory.severity == "high") | .package.name' cargo-audit-report.json | wc -l | tr -d ' ')
          echo "critical=$critical" >> "$GITHUB_OUTPUT"
          echo "high=$high" >> "$GITHUB_OUTPUT"
          if [ "$high" -gt 0 ]; then
            echo "::warning::Detected $high high severity vulnerabilities in Rust dependencies."
          fi
          if [ "$critical" -gt 0 ]; then
            echo "::error::Found $critical critical vulnerabilities in Rust dependencies."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: apps/gateway/package-lock.json

      - name: npm audit
        if: always()
        run: |
          if [ -d "apps/gateway" ]; then
            pushd apps/gateway
            npm ci --no-audit --no-fund
            npm audit --audit-level=moderate --json > ../gateway-audit.json || true
            popd
          else
            echo "Gateway app not found, skipping npm audit."
          fi

      - name: Upload security artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            cargo-audit-report.json
            apps/gateway-audit.json
          retention-days: 30
          if-no-files-found: warn

  sbom:
    name: SBOM Generation
    runs-on: ubuntu-latest
    needs:
      - dependency-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx --locked

      - name: Generate Rust SBOMs
        run: |
          cargo cyclonedx --format json --all
          find . -name "*.cdx.json" -type f > sbom-files-list.txt
          echo "Found $(wc -l < sbom-files-list.txt) CycloneDX files."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Gateway SBOM
        if: always()
        run: |
          if [ -d "apps/gateway" ]; then
            pushd apps/gateway
            npm ci --no-audit
            npx @cyclonedx/cyclonedx-npm --output-file ../../gateway-sbom.json
            popd
          else
            echo "Gateway app not found, skipping SBOM."
          fi

      - name: Generate Unified UI SBOM
        if: always()
        run: |
          if [ -d "apps/unified-ui" ]; then
            pushd apps/unified-ui
            npm ci --no-audit
            npx @cyclonedx/cyclonedx-npm --output-file ../../unified-ui-sbom.json
            popd
          else
            echo "Unified UI app not found, skipping SBOM."
          fi

      - name: Upload SBOM Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx-json
          path: |
            **/*.cdx.json
            gateway-sbom.json
            unified-ui-sbom.json
            sbom-files-list.txt
          retention-days: 90
          if-no-files-found: warn
