name: Auto-merge on green
on:
  pull_request:
    types: [labeled, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prs = (await github.pulls.list({ owner, repo, state: "open" })).data;
            for (const pr of prs) {
              const labels = (await github.issues.listLabelsOnIssue({ owner, repo, issue_number: pr.number })).data.map(l=>l.name);
              if (!labels.includes("automerge")) continue;
              const fresh = (await github.pulls.get({ owner, repo, pull_number: pr.number })).data;
              if (fresh.mergeable_state === "clean") {
                try {
                  await github.pulls.merge({ owner, repo, pull_number: pr.number, merge_method: "squash" });
                } catch (e) { /* try next time */ }
              }
            }
