name: Build & Deploy IPPAN (Docker → Hetzner)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ippan
  COMPOSE_REMOTE_PATH: /opt/ippan/docker-compose.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ "188.245.97.41", "135.181.145.174" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install key & known_hosts (no ssh-add / libcrypto issues)
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HETZNER_SSH_KEY }}          # OpenSSH PRIVATE key (BEGIN/END…)
          name: id_ed25519
          if_key_exists: replace
          known_hosts: |
            188.245.97.41 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICTcMn7PqFxX3w3K/9FMfdE27d2VHRFcQIrdw5WmOnZy
            135.181.145.174 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEUjwwtbcnkKYJIj7ot43Fv3Seeoh+2gqUdqoluXu9tN
          config: |
            Host 188.245.97.41
              User root
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              StrictHostKeyChecking yes
            Host 135.181.145.174
              User root
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              StrictHostKeyChecking yes

      - name: Debug SSH environment
        run: |
          set -x
          ls -la ~/.ssh
          echo "=== SSH config ==="
          cat ~/.ssh/config || true
          echo "=== Known hosts ==="
          wc -l ~/.ssh/known_hosts || true

      - name: Test SSH to host (verbose)
        run: |
          set -x
          ssh -vvv -o BatchMode=yes ${{ matrix.host }} "echo ok"

      - name: Ensure /opt/ippan exists
        run: ssh ${{ matrix.host }} "mkdir -p /opt/ippan"

      - name: Copy deploy dir to server
        run: scp -r deploy/* ${{ matrix.host }}:/opt/ippan/

      - name: Ensure deploy script is executable
        run: ssh ${{ matrix.host }} "chmod +x /opt/ippan/ippan-deploy.sh"

      - name: Deploy remotely
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          set -eo pipefail
          escaped_compose=$(printf %q "${COMPOSE_REMOTE_PATH}")
          escaped_owner=$(printf %q "${REPO_OWNER}")
          escaped_token=$(printf %q "${GHCR_PAT:-}")
          ssh ${{ matrix.host }} "COMPOSE_REMOTE_PATH=$escaped_compose GHCR_USER=$escaped_owner GHCR_TOKEN=$escaped_token bash /opt/ippan/ippan-deploy.sh"

    concurrency:
      group: deploy-main
      cancel-in-progress: false
