name: Open Issue on CI Failure

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  issues: write

jobs:
  open-issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const title = `CI failed: run ${run.id}`;
            const body = `
            The CI workflow failed.

            **Run:** ${run.html_url}

            **Ask (for Codex):**
            - Analyze the failing jobs and error messages.
            - Propose minimal patch to fix the failure.
            - Open/Update the auto-patch PR or comment there.

            _Labels:_ codex, needs-triage
            `;
            const {data: issue} = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['codex','needs-triage']
            });
            core.info('Opened issue #' + issue.number);
