global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ippan_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ippan-nodes'
    static_configs:
      - targets: ['ippan-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['ippan-service:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']