version: '3.8'

services:
  ippan-node:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ippan-node-local
    restart: unless-stopped
    ports:
      - "8080:8080"  # RPC API
      - "9000:9000"  # P2P
    volumes:
      - ./data:/var/lib/ippan
      - ./config/local.env:/etc/ippan/ippan.env:ro
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    networks:
      - ippan-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  ippan-network:
    driver: bridge
