# IPPAN Staging Configuration
# This configuration is optimized for staging environment with testing and debugging features

[network]
# Network configuration for staging
listen_addr = "0.0.0.0:8080"
bootstrap_nodes = [
    "12D3KooWStaging1@staging1.ippan.network:8080",
    "12D3KooWStaging2@staging2.ippan.network:8080"
]
max_connections = 1000
connection_timeout = 30
enable_nat = true
enable_relay = true
enable_dht = true
dht_bootstrap_interval = 300
enable_metrics = true
metrics_port = 9090

# P2P security (relaxed for staging)
enable_tls = false
enable_mutual_auth = false
certificate_path = "/ssl/ippan.crt"
private_key_path = "/ssl/ippan.key"
ca_certificate_path = "/ssl/ca.crt"

[storage]
# Storage configuration for staging
db_path = "/data/ippan.db"
max_storage_size = 107374182400  # 100GB
shard_size = 1048576  # 1MB
replication_factor = 2
enable_encryption = false  # Disabled for staging
encryption_key_path = "/keys/storage.key"
proof_interval = 3600
backup_interval = 86400
backup_retention_days = 7
enable_compression = true
compression_level = 6

# Performance optimizations (reduced for staging)
enable_memory_pool = true
memory_pool_size = 536870912  # 512MB
enable_batch_processing = true
batch_size = 1000
enable_caching = true
cache_size = 1073741824  # 1GB

[consensus]
# Consensus configuration for staging
block_time = 1000  # 1 second for staging
max_block_size = 1048576  # 1MB
validator_count = 5  # Reduced for staging
stake_threshold = 100000000  # 1 IPN for staging
enable_byzantine_tolerance = true
max_byzantine_validators = 1
enable_view_change = true
view_change_timeout = 10000  # 10 seconds
enable_double_spending_detection = true
enable_fork_choice_rule = true

# Performance optimizations
enable_parallel_validation = true
validation_threads = 4
enable_batch_validation = true
batch_validation_size = 100

[api]
# API configuration for staging
listen_addr = "0.0.0.0:3000"
cors_origins = ["*"]
rate_limit = 10000
timeout = 30
enable_metrics = true
metrics_path = "/metrics"
enable_swagger = true
swagger_path = "/docs"
enable_health_check = true
health_check_path = "/health"

# Security (relaxed for staging)
enable_authentication = false
jwt_secret_path = "/keys/jwt.secret"
session_timeout = 3600
enable_rate_limiting = true
rate_limit_window = 60
max_requests_per_window = 10000

[performance]
# Performance configuration for staging
enable_lockfree = true
enable_memory_pool = true
memory_pool_size = 536870912  # 512MB
enable_batch_processing = true
batch_size = 1000
thread_pool_size = 8
enable_caching = true
cache_size = 1073741824  # 1GB
enable_serialization_optimization = true
enable_compression = true
compression_level = 6

# High-throughput optimizations (reduced for staging)
enable_parallel_processing = true
max_concurrent_requests = 10000
enable_streaming = true
streaming_buffer_size = 1048576  # 1MB
enable_zero_copy = true

[security]
# Security configuration (relaxed for staging)
enable_tls = false
enable_mutual_auth = false
certificate_path = "/ssl/ippan.crt"
private_key_path = "/ssl/ippan.key"
ca_certificate_path = "/ssl/ca.crt"
enable_key_rotation = false
key_rotation_interval = 86400  # 24 hours
enable_audit_logging = true
audit_log_path = "/logs/audit.log"
enable_intrusion_detection = false
max_failed_attempts = 10
lockout_duration = 60  # 1 minute

# Encryption (disabled for staging)
enable_storage_encryption = false
storage_encryption_key_path = "/keys/storage.key"
enable_transport_encryption = false
enable_end_to_end_encryption = false

# Key management
enable_quantum_resistant_crypto = false
enable_key_escrow = false
enable_key_recovery = true
key_recovery_threshold = 2

[monitoring]
# Monitoring configuration for staging
enable_prometheus = true
prometheus_port = 9090
enable_grafana = true
grafana_port = 3001
enable_alertmanager = true
alertmanager_port = 9093
enable_log_aggregation = true
log_level = "debug"  # Debug level for staging
log_format = "json"
log_output = "stdout"
enable_structured_logging = true
enable_tracing = true
tracing_endpoint = "http://jaeger:14268/api/traces"

# Metrics
enable_system_metrics = true
enable_application_metrics = true
enable_custom_metrics = true
metrics_retention_days = 7  # Reduced for staging
enable_metrics_export = true
metrics_export_interval = 30

[staking]
# Staking configuration for staging
enable_staking = true
min_stake_amount = 100000000  # 1 IPN for staging
max_stake_amount = 100000000000  # 1,000 IPN for staging
staking_reward_rate = 0.1  # 10% annual for staging
reward_distribution_interval = 3600  # 1 hour for staging
enable_slashing = false  # Disabled for staging
slashing_penalty = 0.1  # 10%
enable_delegation = true
max_delegators_per_validator = 100
delegation_fee_rate = 0.01  # 1% for staging

[wallet]
# Wallet configuration for staging
enable_wallet = true
wallet_db_path = "/data/wallet.db"
enable_multisig = true
max_signatures = 5
enable_hardware_wallet = false  # Disabled for staging
enable_offline_signing = true
enable_transaction_batching = true
batch_size = 100
enable_fee_estimation = true
fee_estimation_window = 10

[dns]
# DNS configuration for staging
enable_dns = true
dns_port = 53
enable_dns_over_https = false  # Disabled for staging
dns_over_https_port = 443
enable_dns_over_tls = false  # Disabled for staging
dns_over_tls_port = 853
enable_dnssec = false  # Disabled for staging
dns_cache_size = 1000
dns_cache_ttl = 300  # 5 minutes for staging
enable_dns_logging = true

[storage_dht]
# Distributed storage configuration for staging
enable_dht = true
dht_port = 4001
enable_file_sharding = true
shard_size = 1048576  # 1MB
replication_factor = 2
enable_erasure_coding = false  # Disabled for staging
erasure_coding_data_shards = 4
erasure_coding_parity_shards = 2
enable_content_addressing = true
enable_deduplication = true
enable_compression = true
compression_level = 6

[crosschain]
# Cross-chain configuration for staging
enable_crosschain = false  # Disabled for staging
enable_bridge = false
bridge_port = 8081
enable_atomic_swaps = false
enable_lightning_network = false
lightning_port = 9735
enable_state_channels = false
max_channel_capacity = 100000000  # 1 IPN for staging
channel_timeout = 3600  # 1 hour for staging

[quantum]
# Quantum computing configuration for staging
enable_quantum_computing = false  # Disabled for staging
quantum_port = 8082
enable_quantum_key_distribution = false
enable_quantum_random_number_generation = false
enable_quantum_encryption = false
quantum_key_size = 256
enable_post_quantum_cryptography = false

[iot]
# IoT configuration for staging
enable_iot = false  # Disabled for staging
iot_port = 8083
enable_edge_computing = false
enable_sensor_data_collection = false
enable_device_management = false
max_devices_per_node = 100
enable_data_aggregation = false
aggregation_interval = 60

[ai]
# AI/ML configuration for staging
enable_ai = false  # Disabled for staging
ai_port = 8084
enable_model_training = false
enable_model_inference = false
enable_federated_learning = false
enable_edge_ai = false
max_model_size = 104857600  # 100MB for staging
enable_model_versioning = false
enable_auto_scaling = false

[logging]
# Logging configuration for staging
level = "debug"  # Debug level for staging
format = "json"
output = "stdout"
enable_file_logging = true
log_file_path = "/logs/ippan.log"
max_log_file_size = 52428800  # 50MB for staging
max_log_files = 5
enable_structured_logging = true
enable_log_rotation = true
enable_log_compression = true
enable_log_aggregation = true
log_aggregation_endpoint = "http://fluentd:24224"

# Performance logging
enable_performance_logging = true
performance_log_path = "/logs/performance.log"
enable_slow_query_logging = true
slow_query_threshold = 1000  # 1 second for staging
enable_memory_logging = true
memory_log_interval = 30  # 30 seconds for staging

[backup]
# Backup configuration for staging
enable_backup = true
backup_interval = 3600  # 1 hour for staging
backup_retention_days = 3  # Reduced for staging
backup_compression = true
backup_encryption = false  # Disabled for staging
backup_encryption_key_path = "/keys/backup.key"
backup_storage_path = "/backups"
enable_incremental_backup = true
enable_cloud_backup = false
cloud_backup_provider = "aws"
cloud_backup_bucket = "ippan-staging-backups"
cloud_backup_region = "us-east-1"

[maintenance]
# Maintenance configuration for staging
enable_auto_maintenance = true
maintenance_interval = 3600  # 1 hour for staging
maintenance_window = "02:00-04:00"
enable_database_optimization = true
enable_index_rebuilding = true
enable_cache_clearing = true
enable_log_cleanup = true
enable_temp_file_cleanup = true
enable_memory_optimization = true

[testing]
# Testing configuration for staging
enable_test_mode = true
enable_mock_data = true
enable_test_transactions = true
enable_debug_endpoints = true
enable_metrics_endpoints = true
enable_health_checks = true
test_data_size = 1000
mock_transaction_count = 100
debug_log_level = "trace"
