name: Android Wallet Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-wallet:
    name: Build Android Wallet
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile/android-wallet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Grant Gradle wrapper permissions
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-wallet-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Attach APK to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
