name: Codex Fix Unified UI (Decommissioned)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Unified UI is no longer managed
        run: |
          echo "::error::The Unified UI has been decommissioned. Use node-only deployment playbooks instead."
          exit 1
