name: Codex Auto PR
on:
  push:
    branches:
      - "codex/**"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.GITHUB_REF_NAME;
            const { data } = await github.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} is:pr is:open head:${branch}`
            });
            if (data.total_count === 0) {
              const pr = await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Codex: ${branch}`,
                head: branch,
                base: 'main',
                body: 'Auto PR created from Codex branch.'
              });
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.data.number,
                labels: ['automerge']
              });
            }
