name: Codex Auto PR
on:
  push:
    branches: ["codex/**"]      # still works if workflow file is on that branch
  create:                        # fires when new branch is created
  schedule:
    - cron: "*/10 * * * *"      # every 10 minutes
  workflow_dispatch:             # manual run button

jobs:
  open-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Open PRs for codex/** without one
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            // List all remote branches under heads/codex/
            const refs = await github.paginate(github.git.listMatchingRefs, {
              owner, repo, ref: "heads/codex/"
            });

            for (const r of refs) {
              const branch = r.ref.replace("refs/heads/", "");
              // Skip if PR already exists
              const prs = await github.paginate(github.pulls.list, {
                owner, repo, state: "open", head: `${owner}:${branch}`, base: "main"
              });
              if (prs.length > 0) continue;

              // Create PR
              const pr = await github.pulls.create({
                owner, repo, title: `Codex: ${branch}`, head: branch, base: "main",
                body: "Auto PR created from Codex branch."
              });

              // Label for auto-merge workflow / policy
              await github.issues.addLabels({
                owner, repo, issue_number: pr.data.number, labels: ["automerge"]
              });
            }
