name: (DEPRECATED) Deploy Unified UI

on:
  workflow_dispatch:

concurrency:
  group: deprecated-deploy-unified-ui
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deprecated — use deploy-ui.yml"
