name: Deploy Unified UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build Unified UI
        working-directory: apps/unified-ui
        env:
          NEXT_PUBLIC_GATEWAY_URL: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL }}
          NEXT_PUBLIC_ENABLE_FULL_UI: ${{ secrets.NEXT_PUBLIC_ENABLE_FULL_UI }}
        run: |
          npm ci
          npm run build

      - name: Install gateway dependencies
        working-directory: apps/gateway
        run: npm ci

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container images
        env:
          IMAGE_PREFIX: ${{ env.IMAGE_PREFIX }}
        run: |
          set -euo pipefail
          IMAGE_PREFIX="${IMAGE_PREFIX,,}"
          docker build -t "$IMAGE_PREFIX/ui:latest" -f apps/unified-ui/Dockerfile apps/unified-ui
          docker build -t "$IMAGE_PREFIX/gateway:latest" apps/gateway
          docker build -t "$IMAGE_PREFIX/node:latest" .
          docker push "$IMAGE_PREFIX/ui:latest"
          docker push "$IMAGE_PREFIX/gateway:latest"
          docker push "$IMAGE_PREFIX/node:latest"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_PREFIX: ${{ env.IMAGE_PREFIX }}
          NEXT_PUBLIC_GATEWAY_URL: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL }}
          NEXT_PUBLIC_ENABLE_FULL_UI: ${{ secrets.NEXT_PUBLIC_ENABLE_FULL_UI }}
          TARGET_RPC_URL: ${{ secrets.TARGET_RPC_URL }}
          TARGET_WS_URL: ${{ secrets.TARGET_WS_URL }}
          TARGET_HEALTH_PATH: ${{ secrets.TARGET_HEALTH_PATH }}
          HEALTH_TIMEOUT_MS: ${{ secrets.HEALTH_TIMEOUT_MS }}
          GATEWAY_ALLOWED_ORIGINS: ${{ secrets.GATEWAY_ALLOWED_ORIGINS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          host: 188.245.97.41
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_PREFIX,NEXT_PUBLIC_GATEWAY_URL,NEXT_PUBLIC_API_BASE_URL,NEXT_PUBLIC_WS_URL,NEXT_PUBLIC_ENABLE_FULL_UI,TARGET_RPC_URL,TARGET_WS_URL,TARGET_HEALTH_PATH,HEALTH_TIMEOUT_MS,GATEWAY_ALLOWED_ORIGINS,GITHUB_TOKEN,GITHUB_ACTOR
          script: |
            set -euo pipefail
            IMAGE_PREFIX="${IMAGE_PREFIX,,}"
            : "${NEXT_PUBLIC_GATEWAY_URL:=https://ui.ippan.org/api}"
            : "${NEXT_PUBLIC_API_BASE_URL:=${NEXT_PUBLIC_GATEWAY_URL}}"
            : "${NEXT_PUBLIC_WS_URL:=wss://ui.ippan.org/ws}"
            : "${NEXT_PUBLIC_ENABLE_FULL_UI:=1}"
            : "${TARGET_RPC_URL:=http://node:8080}"
            : "${TARGET_WS_URL:=ws://node:8080/ws}"
            : "${TARGET_HEALTH_PATH:=/health}"
            : "${HEALTH_TIMEOUT_MS:=5000}"
            : "${GATEWAY_ALLOWED_ORIGINS:=https://ui.ippan.org}"

            mkdir -p /opt/ippan
            cd /opt/ippan

            cat <<EOF > docker-compose.yml
            services:
              ui:
                image: ${IMAGE_PREFIX}/ui:latest
                env_file: .env
                restart: unless-stopped
                networks: [web]
                ports:
                  - "127.0.0.1:3000:3000"
              gateway:
                image: ${IMAGE_PREFIX}/gateway:latest
                env_file: .env
                restart: unless-stopped
                networks: [web]
                depends_on:
                  - node
                ports:
                  - "127.0.0.1:8080:8080"
              node:
                image: ${IMAGE_PREFIX}/node:latest
                env_file: .env
                restart: unless-stopped
                networks: [web]
                ports:
                  - "127.0.0.1:9090:9090"
            networks:
              web:
                driver: bridge
            EOF

            cat <<EOF > .env
            NODE_ENV=production
            NEXT_PUBLIC_GATEWAY_URL=${NEXT_PUBLIC_GATEWAY_URL}
            NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
            NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
            NEXT_PUBLIC_ENABLE_FULL_UI=${NEXT_PUBLIC_ENABLE_FULL_UI}
            ENABLE_FULL_UI=${NEXT_PUBLIC_ENABLE_FULL_UI}
            TARGET_RPC_URL=${TARGET_RPC_URL}
            TARGET_WS_URL=${TARGET_WS_URL}
            TARGET_HEALTH_PATH=${TARGET_HEALTH_PATH}
            HEALTH_TIMEOUT_MS=${HEALTH_TIMEOUT_MS}
            ALLOWED_ORIGINS=${GATEWAY_ALLOWED_ORIGINS}
            EOF

            cat <<'EOF' > /etc/nginx/sites-available/ui.ippan.org
            server {
              listen 80;
              server_name ui.ippan.org;
              return 301 https://$host$request_uri;
            }

            server {
              listen 443 ssl http2;
              server_name ui.ippan.org;

              ssl_certificate     /etc/letsencrypt/live/ui.ippan.org/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/ui.ippan.org/privkey.pem;

              location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto https;
                proxy_read_timeout 300;
              }

              location /api/ {
                proxy_pass http://127.0.0.1:8080/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto https;
                proxy_read_timeout 300;
              }

              location /ws/ {
                proxy_pass http://127.0.0.1:8080/ws/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
              }
            }
            EOF

            ln -sf /etc/nginx/sites-available/ui.ippan.org /etc/nginx/sites-enabled/ui.ippan.org

            docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
            docker compose pull
            docker compose up -d
            docker system prune -f

            nginx -t
            systemctl reload nginx
