name: Deploy Unified UI (Decommissioned)

on:
  workflow_dispatch:
    inputs:
      acknowledgement:
        description: "Type 'I understand' to acknowledge that the Unified UI is no longer deployed."
        required: true
        default: ""

permissions:
  contents: read

jobs:
  abort:
    runs-on: ubuntu-latest
    steps:
      - name: Fail because Unified UI is retired
        run: |
          if [ "${{ github.event.inputs.acknowledgement }}" != 'I understand' ]; then
            echo "::error::Unified UI deployment workflow has been retired. Nodes no longer serve the Unified UI."
          else
            echo "::error::Unified UI deployment workflow has been retired. Nodes no longer serve the Unified UI."
          fi
          exit 1
