name: Verify IPPAN on Hetzner

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [ "188.245.97.41", "135.181.145.174" ]

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HETZNER_SSH_KEY }}
          name: id_ed25519
          if_key_exists: replace
          known_hosts: |
            188.245.97.41 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICTcMn7PqFxX3w3K/9FMfdE27d2VHRFcQIrdw5WmOnZy
            135.181.145.174 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEUjwwtbcnkKYJIj7ot43Fv3Seeoh+2gqUdqoluXu9tN
          config: |
            Host 188.245.97.41 135.181.145.174
              User root
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              StrictHostKeyChecking yes

      - name: Health probes (container, ports, HTTP)
        run: |
          set -euxo pipefail
          echo "=== $(date -u) Checking ${{ matrix.host }} ==="
          ssh ${{ matrix.host }} bash -lc '
            echo "--- compose ps ---"
            docker compose -f /opt/ippan/docker-compose.yml ps || true
            echo "--- docker ps ---"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || true
            echo "--- listeners 3000/7070 ---"
            ss -ltnp 2>/dev/null | grep -E ":3000|:7070" || true
            echo "--- curl localhost:3000/health ---"
            curl -fsS --max-time 5 http://127.0.0.1:3000/health || true
            echo "--- last 80 logs of ippan ---"
            docker logs --tail=80 ippan || true
          '
